DROP TABLE IF EXISTS order_items      CASCADE;
DROP TABLE IF EXISTS orders           CASCADE;
DROP TABLE IF EXISTS cart_items       CASCADE;
DROP TABLE IF EXISTS carts            CASCADE;
DROP TABLE IF EXISTS product_variants CASCADE;
DROP TABLE IF EXISTS product_images   CASCADE;
DROP TABLE IF EXISTS products         CASCADE;
DROP TABLE IF EXISTS categories       CASCADE;
DROP TABLE IF EXISTS user_addresses   CASCADE;
DROP TABLE IF EXISTS user_profiles    CASCADE;
DROP TABLE IF EXISTS users            CASCADE;

DROP FUNCTION IF EXISTS set_updated_at CASCADE;
DROP SEQUENCE IF EXISTS order_number_seq;
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS pgcrypto;
